from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from io import BytesIO

def build_doc(priorities, issues):
    doc = Document()

    title = doc.add_heading("Antora Cost Tracker — Monthly AI Review", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("Generated by AI review workflow")
    run.italic = True
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(0x6B, 0x6B, 0x6B)

    doc.add_heading("Executive Summary", level=1)
    doc.add_paragraph(priorities["summary"])

    doc.add_heading("Top Priorities — Act On These First", level=1)
    for item in priorities["top_priorities"]:
        p = doc.add_paragraph(style="List Number")
        run = p.add_run(item["title"])
        run.bold = True
        p.add_run(f"\nWhy: {item['why']}")
        p.add_run(f"\nRecommended action: {item['recommended_action']}")
        if item.get("owner_suggestion"):
            p.add_run(f"\nSuggested owner: {item['owner_suggestion']}")
        p.add_run(f"\nRelated IDs: {', '.join(item['related_ids'])}")

    doc.add_heading("All Issues Found", level=1)

    doc.add_heading(f"Stale Entries ({len(issues['stale_entries'])})", level=2)
    doc.add_paragraph("Entries with no update in 6+ months. Likely need re-validation or closure.")
    for e in issues["stale_entries"]:
        doc.add_paragraph(
            f"{e['id']} — {e['part_name']}: last updated {e['last_updated']}, ${e['savings']:,} savings",
            style="List Bullet"
        )

    doc.add_heading(f"Duplicates ({len(issues['duplicates'])})", level=2)
    for d in issues["duplicates"]:
        doc.add_paragraph(f"{', '.join(d['ids'])}: {d['reason']}", style="List Bullet")

    doc.add_heading(f"Conflicting Assumptions ({len(issues['conflicting_assumptions'])})", level=2)
    for c in issues["conflicting_assumptions"]:
        doc.add_paragraph(f"{', '.join(c['ids'])}: {c['conflict']}", style="List Bullet")

    doc.add_heading(f"High Savings, No Owner ({len(issues['high_savings_no_owner'])})", level=2)
    for h in issues["high_savings_no_owner"]:
        doc.add_paragraph(
            f"{h['id']} — {h['part_name']}: ${h['savings']:,}",
            style="List Bullet"
        )

    p = doc.add_paragraph()
    run = p.add_run("Generated by the Antora Cost Tracker Review Agent. See companion Excel file for full tracker with highlighted issues.")
    run.italic = True
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x6B, 0x6B, 0x6B)

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf